apiVersion: apps/v1
kind: Deployment
metadata:
  name: '${DEPLOYMENT_GRAPH@microservice-home-config}'
  namespace: '${NAMESPACE@microservice-config}'
  labels:
    app: '${DEPLOYMENT_GRAPH@microservice-home-config}'
    moduleid: microservice-home-graph-service
    version: 1.70.0-reconnect-data-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: '${DEPLOYMENT_GRAPH@microservice-home-config}'
  template:
    metadata:
      labels:
        app: '${DEPLOYMENT_GRAPH@microservice-home-config}'
    spec:
      containers:
        -
          name: app
          image: 'repoflow/microservice-home-graph-container:1.70.0-reconnect-data-prod'
          env:
            -
              name: ROUTE_GRAPH
              value: '${ROUTE_GRAPH@microservice-home-config}'
            -
              name: ROUTE_EVENTS
              value: '${ROUTE_EVENTS@microservice-home-config}'
            -
              name: INTERNAL_PORT_GRAPH
              value: '${INTERNAL_PORT_GRAPH@microservice-home-config}'
            -
              name: INTERNAL_URL_ACCOUNT_GRAPH
              value: '${INTERNAL_URL_GRAPH@microservice-account-config}'
            -
              name: INTERNAL_HOST_CACHE
              value: '${INTERNAL_HOST_CACHE@microservice-auth-config}'
            -
              name: INTERNAL_PORT_CACHE
              value: '${INTERNAL_PORT_CACHE@microservice-auth-config}'
            -
              name: SECRET_PASSWORD_CACHE
              value: SECRET_PASSWORD_CACHE
          ports:
            -
              containerPort: '${INTERNAL_PORT_GRAPH@microservice-home-config}'
