apiVersion: apps/v1
kind: Deployment
metadata:
  name: '${DEPLOYMENT_GRAPH@microservice-home-config}'
  namespace: '${NAMESPACE@microservice-config}'
  labels:
    app: '${DEPLOYMENT_GRAPH@microservice-home-config}'
    moduleid: microservice-home-graph-service
    version: 1.70.3-master
spec:
  replicas: 2
  selector:
    matchLabels:
      app: '${DEPLOYMENT_GRAPH@microservice-home-config}'
  template:
    metadata:
      labels:
        app: '${DEPLOYMENT_GRAPH@microservice-home-config}'
    spec:
      containers:
        -
          name: app
          image: 'repoflow/microservice-home-graph-container:1.70.2-master'
          env:
            -
              name: HOME_ROUTE_GRAPH
              value: '${ROUTE_GRAPH@microservice-home-config}'
            -
              name: HOME_INTERNAL_PORT_GRAPH
              value: '${INTERNAL_PORT_GRAPH@microservice-home-config}'
            -
              name: AUTH_CACHE_INTERNAL_HOST
              value: '${INTERNAL_HOST@microservice-auth-cache-config}'
            -
              name: AUTH_CACHE_INTERNAL_PORT
              value: '${INTERNAL_PORT@microservice-auth-cache-config}'
            -
              name: AUTH_CACHE_SECRET_PASSWORD
              value: SECRET_PASSWORD_CACHE
            -
              name: ACCOUNT_INTERNAL_URL_GRAPH
              value: '${INTERNAL_URL_GRAPH@microservice-account-config}'
          ports:
            -
              containerPort: '${INTERNAL_PORT_GRAPH@microservice-home-config}'
