apiVersion: v1
kind: Service
metadata:
  name: '${SERVICE_GRAPH@microservice-home-config}'
  namespace: '${NAMESPACE@microservice-config}'
  labels:
    moduleid: microservice-home-graph-service
    version: 1.70.4-auth-config-prod
spec:
  type: NodePort
  selector:
    app: '${DEPLOYMENT_GRAPH@microservice-home-config}'
  ports:
    -
      name: microservice-home-graph-port
      port: '${INTERNAL_PORT_GRAPH@microservice-home-config}'
